name: .NET Core

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: your-azure-webapp-name    # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: PacificTours

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: PacificTours

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: PacificTours
