name: Build web app and push to google cloud

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: pacifictourswebapp
      PROJECT_ID: pacifictoursproject
      REPOSITORY_NAME: pacifictoursrepository
      REGION: us-west2

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:$GIT_TAG
        docker push ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest
        docker push ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:$GIT_TAG
  
  deploy-to-google-kubernetes-engine:
    runs-on: ubuntu-latest
    needs: docker

    env:
      PROJECT_ID: pacifictoursproject
      REGION: us-west2
      CLUSTER_NAME: pacifictourswebapp-cluster
      DEPLOYMENT_NAME: pacifictourswebapp-deployment
      IMAGE_NAME: pacifictourswebapp
      REPOSITORY_NAME: pacifictoursrepository
      GIT_TAG: v0.1.0
      CONTAINER_NAME: pacifictourswebapp
    
    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Get GKE Credentials
      run: |-
        gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION --project $PROJECT_ID

    - name: Deploy to GKE
      run: |-
        kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:$GIT_TAG
        kubectl rollout status deployment/$DEPLOYMENT_NAME
